/*
  This class has been generated by the Code Generator
*/

package qa.gov.ashghal.configuration;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.util.logger.CordysLogger;

public class CFM_Agcy extends CFM_AgcyBase
{
static CordysLogger demoLogger = CordysLogger.getCordysLogger(CFM_Agcy.class);
    public CFM_Agcy()
    {
        this((BusObjectConfig)null);
    }

    public CFM_Agcy(BusObjectConfig config)
    {
        super(config);
    }

public void onBeforeInsert() {
  this.setCrtBy(Utility.getUserName());
  this.setCrtOn(Utility.getCurrentDate());
  this.setModBy(Utility.getUserName());
  this.setModOn(Utility.getCurrentDate());
  this.setStatID(1);
  this.setIsMig(false);
 }
 public void onBeforeUpdate() {
  this.setModBy(Utility.getUserName());
  this.setModOn(Utility.getCurrentDate());
 }

// this method fetches all the active agency details
    public static BusObjectIterator<qa.gov.ashghal.configuration.CFM_Agcy> GetActiveAgencies()
    {
      String queryText = "select * from [CFM_Agcy] where [StatID] = '1'";
    QueryObject query = new QueryObject(queryText);
    query.setResultClass(CFM_Agcy.class);
    return query.getObjects();
    }

    public static qa.gov.ashghal.configuration.CFM_Agcy GetAgencyByAgencyCode(String AgcyCode)
    {
        String queryText = "select [AgcyID],[AgcyEnNm],[AgcyCd] from [CFM_Agcy] where [AgcyCd] = :AgcyCode and [StatID] = '1'";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("AgcyCode", "CFM_Agcy.AgcyCd", QueryObject.PARAM_STRING, new String(AgcyCode));//NOPMD
        query.setResultClass(CFM_Agcy.class);
        return (CFM_Agcy)query.getObject();
    }

	 public static BusObjectIterator<qa.gov.ashghal.configuration.CFM_Agcy> GetAgenciesByAgcyCodes(String AgencyID)
    {
        String queryText = "select * from CFM_Agcy where AgcyCdSys in ("+AgencyID+") and StatID = '1' order by AgcyCdSys asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("AgencyID", "CFM_Agcy.AgcyCdSys", QueryObject.PARAM_STRING, new String(AgencyID));//NOPMD
        query.setResultClass(CFM_Agcy.class);
        return query.getObjects();
    }
	
    public static qa.gov.ashghal.configuration.CFM_Agcy GetAgencyByAgencyCodeSys(String strAgencyCodeSys)
    {
        String queryText = "select [AgcyID],[AgcyEnNm],[AgcyArNm],[AgcyCd],[AgcyTypID] from [CFM_Agcy] where [AgcyCdSys] = :AgcyCodeSys and [StatID] = '1'";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("AgcyCodeSys", "CFM_Agcy.AgcyCdSys", QueryObject.PARAM_STRING, new String(strAgencyCodeSys));//NOPMD
        query.setResultClass(CFM_Agcy.class);
        return (CFM_Agcy)query.getObject();
    }
 
// this method fetches all the active agency details based on search
  public static BusObjectIterator<qa.gov.ashghal.configuration.CFM_Agcy> GetAgencyDetailsOnSearch(String AgcyName, String AgcyCode, String AgcyAra, String ConcDept, String Email, String Status)
    {      
demoLogger.error("Error Occurred:"  + AgcyName );
AgcyName = (AgcyName == null) ? "" : AgcyName;
AgcyCode= (AgcyCode== null) ? "" : AgcyCode;
AgcyAra = (AgcyAra == null) ? "" : AgcyAra;
ConcDept = (ConcDept == null) ? "" : ConcDept;
Email = (Email == null) ? "" : Email;
Status = (Status == null) ? "" : Status;

demoLogger.error("Error Occurred1:"  + AgcyName );
        String queryText="select * from CFM_Agcy where StatID in (1,2) ";   
		if(!AgcyName.isEmpty())
		{
			queryText+="and AgcyEnNm like Concat('%',:AgcyName,'%') ";				
		}	
		if(!AgcyCode.isEmpty())
		{
			queryText+="and AgcyCd like Concat('%',:AgcyCode,'%') ";				
		}
		if(!AgcyAra.isEmpty())
		{
			queryText+="and AgcyArNm like Concat('%',:AgcyAra,'%') ";				
		}
		if(!ConcDept.isEmpty())		
		{	
			queryText+="and ConcDept like Concat('%',:ConcDept,'%') ";				
		}
		if(!Email.isEmpty())
		{
			queryText+="and EmailDom like Concat('%',:Email,'%') ";				
		}
		if(!Status.isEmpty())
		{
			queryText+="and StatID = :Status ";			
		}
		 QueryObject query = new QueryObject(queryText);
		 query.addParameter("AgcyName", "CFM_Agcy.AgcyEnNm", QueryObject.PARAM_STRING, new String(AgcyName));
		 query.addParameter("AgcyCode", "CFM_Agcy.AgcyCd", QueryObject.PARAM_STRING, new String(AgcyCode));
		 query.addParameter("AgcyAra", "CFM_Agcy.AgcyArNm", QueryObject.PARAM_STRING, new String(AgcyAra));
		 query.addParameter("ConcDept", "CFM_Agcy.ConcDept", QueryObject.PARAM_STRING, new String(ConcDept));
		 query.addParameter("Email", "CFM_Agcy.EmailDom", QueryObject.PARAM_STRING, new String(Email));
		 query.addParameter("Status", "CFM_Agcy.StatID", QueryObject.PARAM_STRING, new String(Status));
		 query.setResultClass(CFM_Agcy.class);
		 return query.getObjects();
  }

    public static BusObjectIterator<qa.gov.ashghal.configuration.CFM_Agcy> getCFM_AgcyObjectsForStatID(int StatID)
    {
//StatID = (StatID == null) ? 0 : StatID;
      String queryText = "select * from \"CFM_Agcy\" where \"StatID\" = :StatID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("StatID", "CFM_Agcy.StatID", QueryObject.PARAM_INT, new Integer(StatID));//NOPMD
        query.setResultClass(CFM_Agcy.class);
        return query.getObjects();
    }
	// this method fetch the agency id used by submission agency
	  public static BusObjectIterator<qa.gov.ashghal.configuration.CFM_Agcy> IsAgencyUse(String AgencyID)
    {
AgencyID = (AgencyID == null) ? "" : AgencyID;
         String queryText = "select count(ag.AgcyID) as agcCount from CFM_Agcy ag where exists(select * from CFM_SbmsPrdAgcy sp where sp.AgcyID=ag.AgcyID and ag.AgcyID=:AgencyID) or exists(select * from CFM_PndExtnUsrActvn pd where pd.ExtnUsrSrcID=ag.AgcyID and ag.AgcyID=:AgencyID and pd.ExtnUsrTypID = '5')";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("AgencyID", "CFM_Agcy.AgencyID", QueryObject.PARAM_STRING, new String(AgencyID));//NOPMD
        query.setResultClass(CFM_Agcy.class);
        return query.getObjects();
    }

}
